// POST TYPES
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_POST = "GET_POST";
export const CREATE_POST = "CREATE_POST";
export const DELETE_POST = "DELETE_POST";
export const POSTS_LOADING = "POSTS_LOADING";

// COVID POSTS TYPES
export const GET_ALL_C_POSTS = "GET_ALL_C_POSTS";
export const GET_C_POST = "GET_C_POST";
export const CREATE_C_POST = "CREATE_C_POST";
export const DELETE_C_POST = "DELETE_C_POST";
export const C_POSTS_LOADING = "C_POSTS_LOADING";

// USER TYPES
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

// AUTH TYPES
export const AUTH_ERROR = "AUTH_ERROR";

// LOGIN/REGISTER/LOGOUT TYPES
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// ERROR TYPES
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
